[project]
name = "HeliWatch"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.14.2",
    "nodriver>=0.48.0",
    "requests>=2.32.5",
]

[tool.uv.workspace]
members = [
    "ADSB/ICAO_8643_50",
]
